apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_SERVER_ID: "1"
  ZOOKEEPER_SERVERS: zookeeper:2888:3888

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  clusterIP: None
  ports:
    - port: 2181
      name: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper # provides association with our previously created zookeeper Service.
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.2.1
          envFrom:
            - configMapRef:
                name: zookeeper
          ports:
            - containerPort: 2181
              name: zookeeper
              protocol: TCP
