apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      name: get-logs
    - port: 9600
      name: logstash-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.17.6
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            # - name: config
            #   mountPath: /usr/share/logstash/config/logstash.yaml
            #   readOnly: true
            #   subPath: logstash.yaml
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          ports:
            - containerPort: 5044
              name: get-logs
              protocol: TCP
            - containerPort: 9600
              name: logstash-api
              protocol: TCP
      volumes:
        # Bind previously defined ConfigMap
        # - name: config
        #   configMap:
        #     name: logstash-config
        - name: pipeline
          configMap:
            name: logstash-pipeline
        

